name: Build-sphinx-docs

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
           python-version: "3.9"
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
    
      - name: Build HTML
        run: | 
          cd docs
          make html

      - name: Run ghp-import
        run: | 
          ghp-import -npfo docs/build/html